In [1]:
import numpy as np

In [8]:
arr = np.random.randint(1, 20, (4, 4))
sorted_array = np.sort(arr, axis=0)

print(f"Original 4x4 array:\n{arr}")
print(f"\nColumn-wise sorted array:\n{sorted_array}")

Original 4x4 array:
[[ 4 14 13  7]
 [17 12 17 12]
 [ 2  4  4 10]
 [ 8  4 11 13]]

Column-wise sorted array:
[[ 2  4  4  7]
 [ 4  4 11 10]
 [ 8 12 13 12]
 [17 14 17 13]]
