In [1]:
import numpy as np

In [8]:
def median(arr):
    return np.median(arr)

def mode(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    return values[counts == max_count]

arrays = [np.random.randint(0, 10, (3, 3)), np.random.randint(0, 10, (4, 4)), np.random.randint(0, 10, (2, 5))]

for i, arr in enumerate(arrays):
    print(f"Array {i}:\n{arr}")
    print(f"Median: {median(arr)}, Mode: {mode(arr)}\n")

Array 0:
[[5 6 0]
 [7 0 7]
 [8 0 2]]
Median: 5.0, Mode: [0]

Array 1:
[[9 6 4 0]
 [6 5 4 4]
 [8 3 9 0]
 [2 7 6 1]]
Median: 4.5, Mode: [4 6]

Array 2:
[[0 5 9 7 1]
 [5 7 3 2 8]]
Median: 5.0, Mode: [5 7]

