In [1]:
import numpy as np

array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])

# (a) Vertical Stacking: Create a 4x2 array (array3)
array3 = np.vstack((array1, array2))
print(f"Array3: \n{array3}\n")

# (b) Horizontal Stacking: Create a 2x4 array (array4)
array4 = np.hstack((array1, array2))
print(f"Array4: \n{array4}\n")

# (c) Vertical Stacking with Two Copies of array4: Create a 4x4 array (array5)
array5 = np.vstack((array4, array4))
print(f"Array5: \n{array5}\n")

# (d) Horizontal Stacking with Two Copies of array3: Create a 4x4 array (array6)
array6 = np.hstack((array3, array3))
print(f"Array6: \n{array6}\n")

Array3: 
[[0 1]
 [2 3]
 [4 5]
 [6 7]]

Array4: 
[[0 1 4 5]
 [2 3 6 7]]

Array5: 
[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]

Array6: 
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]

