In [16]:
import numpy as np

# One dimensional array
numbers = np.array([10, 20, 50, 40, 30])
print(f"1D array: \n{numbers}")
print(f"Type of 1D array: {type(numbers)}")

print()

# Two dimensional array
numbers_2d = np.array([[1, 2, 3], [4, 6, 5]])
print(f"2D array: \n{numbers_2d}")
print(f"Type of 2D array: {type(numbers_2d)}")

1D array: 
[10 20 50 40 30]
Type of 1D array: <class 'numpy.ndarray'>

2D array: 
[[1 2 3]
 [4 6 5]]
Type of 2D array: <class 'numpy.ndarray'>


In [21]:
print(f"dtype: {numbers_2d.dtype}")
print(f"ndim: {numbers_2d.ndim}")
print(f"shape: {numbers_2d.shape}")
print(f"size: {numbers_2d.size}")

dtype: int64
ndim: 2
shape: (2, 3)
size: 6


In [27]:
print("1D array: ")
for i in numbers:
    print(i, end = ' ')
print()
print("\n2D array: ")
for i in numbers_2d:
    for j in i:
        print(j, end = ' ')
    print()

1D array: 
10 20 50 40 30 

2D array: 
1 2 3 
4 6 5 


In [32]:
arr_zeros = np.zeros([3, 4])
print(f"Array with all zeros: \n{arr_zeros}")
print(f"Type: {arr_zeros.dtype}")

Array with all zeros: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Type: float64


In [33]:
arr_ones = np.ones([3, 4])
print(f"Array with all ones: \n{arr_ones}")
print(f"Type: {arr_ones.dtype}")

Array with all ones: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Type: float64


In [35]:
arr_els = np.full([3, 4], 5)
print(f"Array with all 5's: \n{arr_els}")
print(f"Type: {arr_els.dtype}")

Array with all 5's: 
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Type: int64


In [40]:
# arange function
arr_r = np.arange(11)
print(f"arr_r: {arr_r}")

arr_r1 = np.arange(1, 11, 2)
print(f"arr_r1: {arr_r1}")

arr_r: [ 0  1  2  3  4  5  6  7  8  9 10]
arr_r1: [1 3 5 7 9]


In [42]:
# linspace
arr_l = np.linspace(0, 1, 5)
print(f"arr_l: {arr_l}")

arr_l: [0.   0.25 0.5  0.75 1.  ]


In [52]:
# reshape
arr_r2 = np.array([[1,2,3], [4,5,6]])
arr_r2 = arr_r2.reshape(3, 2)
print(f"arr_r2: \n{arr_r2}")

arr_r2: 
[[1 2]
 [3 4]
 [5 6]]


In [56]:
arr_ones = np.ones([1000, 500])
print(f"arr_ones: \n{arr_ones}")

arr_ones: 
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [78]:
# random function in numpy lib
np.random.randint(2, 110)

50

In [87]:
# Time comparision
from random import randrange as r
%timeit li = [r(1, 11) for _ in range(10000)]
%timeit li = np.full([10000], np.random.randint(1, 11))

2.77 ms ± 77.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
7.11 µs ± 69.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [93]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
print(f"arr1 * 5: {arr1 * 5}")
print(f"arr1 ** 2: {arr1 ** 2}")
print(f"arr1 / 2: {arr1 / 2}")
print(f"arr1: {arr1}")

arr1 * 5: [ 5 10 15 20 25 30]
arr1 ** 2: [ 1  4  9 16 25 36]
arr1 / 2: [0.5 1.  1.5 2.  2.5 3. ]
arr1: [1 2 3 4 5 6]


In [120]:
a = np.arange(1, 11)
b = np.arange(5, 15)

print(f"a + b: {a + b}\n")
print(f"a - b: {a - b}\n")
print(f"a * b: {a * b}\n")
print(f"a / b: {(a / b)}\n")

print(f"a == b: {a == b}\n")
print(f"a > b: {a > b}\n")
print(f"a < b: {a < b}\n")



a + b: [ 6  8 10 12 14 16 18 20 22 24]

a - b: [-4 -4 -4 -4 -4 -4 -4 -4 -4 -4]

a * b: [  5  12  21  32  45  60  77  96 117 140]

a / b: [0.2        0.33333333 0.42857143 0.5        0.55555556 0.6
 0.63636364 0.66666667 0.69230769 0.71428571]

a == b: [False False False False False False False False False False]

a > b: [False False False False False False False False False False]

a < b: [ True  True  True  True  True  True  True  True  True  True]



In [129]:
# sum()

print(f"a: \n{a}\n")

print(f"a.sum() before reshaping: {a.sum()}")
a = a.reshape(2, 5)
print(f"a.sum() after reshaping: {a.sum()}\n")

print(f"a.sum(axis = 0): {a.sum(axis = 0)}")
print(f"a.sum(axis = 1): {a.sum(axis = 1)}")

a: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

a.sum() before reshaping: 55
a.sum() after reshaping: 55

a.sum(axis = 0): [ 7  9 11 13 15]
a.sum(axis = 1): [15 40]


In [166]:
grades = np.full([12], np.random.randint(60, 101, 12))
print(grades)
grades = grades.reshape([3, 4])

average = np.mean(grades)
print(f"Average of class : {(average):.2f}")

col_sum = grades.sum(axis = 0)
col_avg = col_sum / 3
print(f"Averages of columns: {col_avg}")

row_sum = grades.sum(axis = 1)
row_avg = row_sum / 4
print(f"Averages of rows: {row_avg}")

[ 77 100  88  88  88  84  94  75  81  88  92  92]
Average of class : 87.25
Averages of columns: [82.         90.66666667 91.33333333 85.        ]
Averages of rows: [88.25 85.25 88.25]
