In [1]:
import numpy as np

In [2]:
# lists
a = [10, 5, 20]
b = [15, 5, 25]

print(f"a + b: {a + b}\na * 4: {a * 4}")

a + b: [10, 5, 20, 15, 5, 25]
a * 4: [10, 5, 20, 10, 5, 20, 10, 5, 20, 10, 5, 20]


In [3]:
# arrays

a = np.array([4, 3, 6, 1, 5, 5.5])
print(f"a: {a}")

b = np.array([ [20, 50], [30, 10] ])
print(f"b:\n{b}\n")

c = np.array([4,5,"M"])
print(f"c:\n{c}\n")

print(f"type(a): {type(a)}")

print(f"a.dtype: {a.dtype}")
print(f"b.dtype: {b.dtype}")
print(f"c.dtype: {c.dtype}\n")

print(f"a.ndim: {a.ndim}")
print(f"b.ndim: {b.ndim}\n")

print(f"a.shape: {a.shape}")
print(f"b.shape: {b.shape}\n")

print(f"a.size: {a.size}")
print(f"b.itemsize: {b.itemsize}\n")

print(f"Elements of b: ")
for i in b:
    print(i, end = ' ')

a: [4.  3.  6.  1.  5.  5.5]
b:
[[20 50]
 [30 10]]

c:
['4' '5' 'M']

type(a): <class 'numpy.ndarray'>
a.dtype: float64
b.dtype: int32
c.dtype: <U11

a.ndim: 1
b.ndim: 2

a.shape: (6,)
b.shape: (2, 2)

a.size: 6
b.itemsize: 4

Elements of b: 
[20 50] [30 10] 

In [4]:
zeros = np.zeros(5)
print(f"zeros: {zeros}\n")

zeros2d = np.zeros((3, 6))
print(f"zeros2d: \n{zeros2d}\n")

full = np.full(5, 22)
print(f"full: {full}\n")

full2d = np.full((2, 4), 35)
print(f"full2d: \n{full2d}\n")

range_arr1 = np.arange(8)
print(f"range_arr1: {range_arr1}")
range_arr2 = np.arange(2, 7)
print(f"range_arr2: {range_arr2}")
range_arr3 = np.arange(3, 19, 2)
print(f"range_arr3: {range_arr3}\n")

linspace_arr1 = np.linspace(5, 10)
print(f"linspace_arr1: {linspace_arr1}\n")
linspace_arr2 = np.linspace(5, 10, 15)
print(f"linspace_arr2: {linspace_arr2}\n")

zeros: [0. 0. 0. 0. 0.]

zeros2d: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

full: [22 22 22 22 22]

full2d: 
[[35 35 35 35]
 [35 35 35 35]]

range_arr1: [0 1 2 3 4 5 6 7]
range_arr2: [2 3 4 5 6]
range_arr3: [ 3  5  7  9 11 13 15 17]

linspace_arr1: [ 5.          5.10204082  5.20408163  5.30612245  5.40816327  5.51020408
  5.6122449   5.71428571  5.81632653  5.91836735  6.02040816  6.12244898
  6.2244898   6.32653061  6.42857143  6.53061224  6.63265306  6.73469388
  6.83673469  6.93877551  7.04081633  7.14285714  7.24489796  7.34693878
  7.44897959  7.55102041  7.65306122  7.75510204  7.85714286  7.95918367
  8.06122449  8.16326531  8.26530612  8.36734694  8.46938776  8.57142857
  8.67346939  8.7755102   8.87755102  8.97959184  9.08163265  9.18367347
  9.28571429  9.3877551   9.48979592  9.59183673  9.69387755  9.79591837
  9.89795918 10.        ]

linspace_arr2: [ 5.          5.35714286  5.71428571  6.07142857  6.42857143  6.78571429
  7.14285714  7.5         7.

In [5]:
# Reshaping arrays
arr = np.array([4, 2, 3, 8, 9, 11])
reshape_arr = arr.reshape(2,3)
print(f"reshape_arr: \n{reshape_arr}\n")

# Displaying large arrays
large_array = np.arange(100000)
print(f"large_array: {large_array}\n")
reshaped_array = large_array.reshape(10, 10000)
print(f"reshaped_array: \n{reshaped_array}")

reshape_arr: 
[[ 4  2  3]
 [ 8  9 11]]

large_array: [    0     1     2 ... 99997 99998 99999]

reshaped_array: 
[[    0     1     2 ...  9997  9998  9999]
 [10000 10001 10002 ... 19997 19998 19999]
 [20000 20001 20002 ... 29997 29998 29999]
 ...
 [70000 70001 70002 ... 79997 79998 79999]
 [80000 80001 80002 ... 89997 89998 89999]
 [90000 90001 90002 ... 99997 99998 99999]]


In [6]:
# %timeit
%timeit list_ = [i for i in range(5, 100000000)]
%timeit array_ = np.arange(5, 100000000)

3.3 s ± 111 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
103 ms ± 6.87 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
# array operators

# the shapes of both the arrays must be same to perform array operations
arr1 = np.array([3, 2, 1, 8, 6])
arr2 = np.array([4, 1, 1, 2, 2])

print(f"arr1 + arr2: {arr1 + arr2}")
print(f"arr1 ** 2: {arr1 ** 2}")

arr3 = arr1 ** 3   # augmented assignments
arr3

arr1 + arr2: [ 7  3  2 10  8]
arr1 ** 2: [ 9  4  1 64 36]


array([ 27,   8,   1, 512, 216], dtype=int32)

In [8]:
# boolean operators

arr1 = np.array([3, 2, 1, 8, 6])
arr2 = np.array([8, 4, 1, 2, 2])

print(f"arr1 > arr2: {arr1 > arr2}")
print(f"arr2 >= 3: {arr2 >= 3}")

arr1 > arr2: [False False False  True  True]
arr2 >= 3: [ True  True False False False]


In [9]:
# NumPy calculation methods

grades = np.array([5, 3, 2, 11, 8])
print(f"grades.sum(): {grades.sum()}")   # using instance method
print(f"np.sum(grades): {np.sum(grades)}\n")   # using standalone function

print(f"grades.mean(): {grades.mean()}")   # using instance method
print(f"np.mean(grades): {np.mean(grades)}\n")   # using standalone function

print(f"grades.std(): {grades.std()}")   # using instance method
print(f"np.std(grades): {np.std(grades)}\n")   # using standalone function

print(f"grades.var(): {grades.var()}")   # using instance method
print(f"np.var(grades): {np.var(grades)}\n")   # using standalone function

print(f"grades.min(): {grades.min()}")   # using instance method
print(f"np.min(grades): {np.min(grades)}\n")   # using standalone function

print(f"grades.max(): {grades.max()}")   # using instance method
print(f"np.max(grades): {np.max(grades)}\n")   # using standalone function

grades.sum(): 29
np.sum(grades): 29

grades.mean(): 5.8
np.mean(grades): 5.8

grades.std(): 3.3105890714493698
np.std(grades): 3.3105890714493698

grades.var(): 10.96
np.var(grades): 10.96

grades.min(): 2
np.min(grades): 2

grades.max(): 11
np.max(grades): 11



In [10]:
# Calculations by rows or columns

grades = np.array([[5, 3, 2, 11, 8], [2, 3, 34, 22, 11]])

print(f"grades.sum(axis = 0): {grades.sum(axis = 0)}")   # sum of each columns
print(f"grades.sum(axis = 1): {grades.sum(axis = 1)}\n")   # sum of each rows

print(f"grades.mean(axis = 0): {grades.mean(axis = 0)}")
print(f"grades.mean(axis = 1): {grades.mean(axis = 1)}\n")

print(f"grades.min(axis = 0): {grades.min(axis = 0)}")
print(f"grades.max(axis = 1): {grades.max(axis = 1)}")

grades.sum(axis = 0): [ 7  6 36 33 19]
grades.sum(axis = 1): [29 72]

grades.mean(axis = 0): [ 3.5  3.  18.  16.5  9.5]
grades.mean(axis = 1): [ 5.8 14.4]

grades.min(axis = 0): [ 2  3  2 11  8]
grades.max(axis = 1): [11 34]


In [11]:
# random number generation

nums = np.random.randint(60, 100, size = 12)
# nums2 = np.array(np.random.randint(60, 100, 12))
# nums3 = np.array([np.random.randint(60, 100) for _ in range(12)])

nums = nums.reshape((3, 4))

print(f"All grades: \n{nums}\n")
print(f"The average of all the grades in each column: {nums.mean(axis = 0)}")
print(f"The average of all the grades in each row: {nums.mean(axis = 1)}")

All grades: 
[[99 77 76 76]
 [79 94 77 93]
 [67 62 62 86]]

The average of all the grades in each column: [81.66666667 77.66666667 71.66666667 85.        ]
The average of all the grades in each row: [82.   85.75 69.25]


In [12]:
# Slicing

arr = np.array([45, 90, 25, 50, 35, 70, 15, 30, 65, 70, 130])

print(f"arr[4]: {arr[4]}")
print(f"arr[2 : 5]: {arr[2 : 5]}")
print(f"arr[ : 4]: {arr[ : 4]}")
print(f"arr[arr > 45]: {arr[arr > 45]}\n")


arr2d = np.array([[20, 30, 10, 50], [35, 25, 75, 15]])

print(f"arr2d[1, 2]: {arr2d[1, 2]}\n")

print(f"arr2d[0 : 2, 0 : 2]: \n{arr2d[0 : 2, 0 : 2]}\n")

print(f"arr2d[ : , : 2]: \n{arr2d[ : , : 2]}\n")

print(f"arr2d[0, 1 : 3]: {arr2d[0, 1 : 3]}")

print(f"arr2d[ : , 2]: {arr2d[ : , 2]}\n")

print(f"arr2d[1, 1 : 4]: {arr2d[1, 1 : 4]}\n")

print(f"arr2d[ : , [1, 3]]: \n{arr2d[ : , [1, 3]]}\n")

print(f"arr2d[arr2d > 20]: {arr2d[arr2d > 25]}")

arr[4]: 35
arr[2 : 5]: [25 50 35]
arr[ : 4]: [45 90 25 50]
arr[arr > 45]: [ 90  50  70  65  70 130]

arr2d[1, 2]: 75

arr2d[0 : 2, 0 : 2]: 
[[20 30]
 [35 25]]

arr2d[ : , : 2]: 
[[20 30]
 [35 25]]

arr2d[0, 1 : 3]: [30 10]
arr2d[ : , 2]: [10 75]

arr2d[1, 1 : 4]: [25 75 15]

arr2d[ : , [1, 3]]: 
[[30 50]
 [25 15]]

arr2d[arr2d > 20]: [30 50 35 75]


In [13]:
arr_ = np.arange(10, 151, 10).reshape(3, 5)

print(f"arr_:\n{arr_}\n")
print(f"Second row: {arr_[1]}\n")
print(f"First and third rows: \n{arr_[[0, 2], : ]}\n")
print(f"Middle three columns: \n{arr_[ : , 1 : 4]}\n")
print(f"Sum of middle three columns: {arr_[ : , 1 : 4].sum(axis = 0)}")

arr_:
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]

Second row: [ 60  70  80  90 100]

First and third rows: 
[[ 10  20  30  40  50]
 [110 120 130 140 150]]

Middle three columns: 
[[ 20  30  40]
 [ 70  80  90]
 [120 130 140]]

Sum of middle three columns: [210 240 270]


In [14]:
# view: shallow copies

a = np.array([5, 4, 3, 2, 8, 9])
b = a.view()

print(f"a: {a}")
print(f"b: {b}\n")

a[1] = 44
print(f"a: {a}")
print(f"b: {b}\n\n")

c = a[2 : ]
print(f"a: {a}")
print(f"c: {c}\n")

c[3] = 99
print(f"a: {a}")
print(f"c: {c}")

a: [5 4 3 2 8 9]
b: [5 4 3 2 8 9]

a: [ 5 44  3  2  8  9]
b: [ 5 44  3  2  8  9]


a: [ 5 44  3  2  8  9]
c: [3 2 8 9]

a: [ 5 44  3  2  8 99]
c: [ 3  2  8 99]


In [15]:
# copy: Deep copies

a = np.array([5, 4, 3, 2, 8, 9])
b = a.copy()

print(f"a: {a}")
print(f"b: {b}\n")

a[1] = 44
print(f"a: {a}")
print(f"b: {b}\n\n")

a: [5 4 3 2 8 9]
b: [5 4 3 2 8 9]

a: [ 5 44  3  2  8  9]
b: [5 4 3 2 8 9]




In [16]:
# Reshaping arrays

# reshape()
a = np.array([2,3,4,5,6,8])
print(f"a.reshape((2,3)):\n{a.reshape((2,3))}\n")  # shallow copy of the original array

print(f"a: \n{a}\n")

# resize()
a.resize((2,3))   # modifies the original array's shape
print(f"a: \n{a}\n")


b = np.array([[5,3,1,9], [88,25,15,20]])
# flatten()   # deep copy of flattened original array
c = b.flatten()
c[1] = 787

print(f"b: \n{b}\n")
print(f"c: {c}\n")

# ravel()   # shallow copy of flattened original array
c = b.ravel()
c[2] = 454
print(f"b: {b}\n")
print(f"c: {c}\n")

a.reshape((2,3)):
[[2 3 4]
 [5 6 8]]

a: 
[2 3 4 5 6 8]

a: 
[[2 3 4]
 [5 6 8]]

b: 
[[ 5  3  1  9]
 [88 25 15 20]]

c: [  5 787   1   9  88  25  15  20]

b: [[  5   3 454   9]
 [ 88  25  15  20]]

c: [  5   3 454   9  88  25  15  20]



In [17]:
# Transposing

a = np.array([[1,2,3,4,5], [7,8,9,10,11]])
a.T   # transpose
# a.T.T   # transpose of transpose(original array)

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [18]:
# horizontal and vertical stacking

grades = np.array ([[100 , 96 , 70] , [100 , 87 , 90]])
grades2 = np.array ([[94 , 77 , 90, 14] , [100 , 81 , 82, 18]])
grades3 = np.array([[33, 44, 55], [88, 99, 77]])
grades4 = np.array([[1,2,3], [4,5,6]])

hor = np.hstack((grades, grades2, grades3))    # horizontal stacking needs both the arrays to have the same no. of rows
print(f"horizontal stack: \n{hor}\n")

ver = np.vstack((grades, grades3, grades4))   # vertical stacking needs both the arrays to have the same no. of columns
print(f"vertical stack: \n{ver}")

horizontal stack: 
[[100  96  70  94  77  90  14  33  44  55]
 [100  87  90 100  81  82  18  88  99  77]]

vertical stack: 
[[100  96  70]
 [100  87  90]
 [ 33  44  55]
 [ 88  99  77]
 [  1   2   3]
 [  4   5   6]]


In [19]:
# Searching arrays
arr = np.array([1,3,5,2,14,7,2,3,2,8,7,3])

indices_of_7 = np.where(arr == 7)
print(f"Element 7 is present at: {indices_of_7}")

indices_of_even = np.where(arr % 2 == 0)
print(f"Even numbers are present at indices: {indices_of_even}\n")

indices_of_odd = np.where(arr % 2)
print(f"Odd numbers are present at indices: {indices_of_odd}\n")

arr2d = np.array([[3,21,11], [5,4,33], [33, 11, 8], [33,11,4]])
print(f"Element 33 is present at indices: {np.where(arr2d == 33)}\nElement 11 is present at indices: {np.where(arr2d == 11)}")

Element 7 is present at: (array([ 5, 10], dtype=int64),)
Even numbers are present at indices: (array([3, 4, 6, 8, 9], dtype=int64),)

Odd numbers are present at indices: (array([ 0,  1,  2,  5,  7, 10, 11], dtype=int64),)

Element 33 is present at indices: (array([1, 2, 3], dtype=int64), array([2, 0, 0], dtype=int64))
Element 11 is present at indices: (array([0, 2, 3], dtype=int64), array([2, 1, 1], dtype=int64))


In [20]:
# Sorting arrays
arr = np.array([10,3,15,2,14,7,42,3,22,8,7,3])

sorted_arr = np.sort(arr)
print(f"Sorted array is: {sorted_arr}")

arr_2d = np.sort(np.array([[3,21,1], [5,4,33], [23, 11, 8]]))
print(f"Sorted array2d is: \n{arr_2d}")

Sorted array is: [ 2  3  3  3  7  7  8 10 14 15 22 42]
Sorted array2d is: 
[[ 1  3 21]
 [ 4  5 33]
 [ 8 11 23]]


In [21]:
chars = np.array('Debadarshi Omkar', dtype = 'U10')
print(chars)

Debadarshi
