In [2]:
import numpy as np

In [3]:
# lists
a = [10, 5, 20]
b = [15, 5, 25]

print(f"a + b: {a + b}\na * 4: {a * 4}")

a + b: [10, 5, 20, 15, 5, 25]
a * 4: [10, 5, 20, 10, 5, 20, 10, 5, 20, 10, 5, 20]


In [25]:
# arrays

a = np.array([4, 3, 6, 1, 5])
print(f"a: {a}")

b = np.array([ [20, 50], [30, 10] ])
print(f"b:\n{b}\n")

print(f"type(a): {type(a)}")

print(f"a.dtype: {a.dtype}")
print(f"b.dtype: {b.dtype}\n")

print(f"a.ndim: {a.ndim}")
print(f"b.ndim: {b.ndim}\n")

print(f"a.shape: {a.shape}")
print(f"b.shape: {b.shape}\n")

print(f"a.size: {a.size}")
print(f"b.itemsize: {b.itemsize}\n")

print(f"Elements of b: ")
for i in b:
    print(i, end = ' ')

a: [4 3 6 1 5]
b:
[[20 50]
 [30 10]]

type(a): <class 'numpy.ndarray'>
a.dtype: int32
b.dtype: int32

a.ndim: 1
b.ndim: 2

a.shape: (5,)
b.shape: (2, 2)

a.size: 5
b.itemsize: 4

Elements of b: 
[20 50] [30 10] 

In [39]:
zeros = np.zeros(5)
print(f"zeros: {zeros}\n")

zeros2d = np.zeros((3, 6))
print(f"zeros2d: \n{zeros2d}\n")

full = np.full(5, 22)
print(f"full: {full}\n")

full2d = np.full((2, 4), 35)
print(f"full2d: \n{full2d}")

zeros: [0. 0. 0. 0. 0.]

zeros2d: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

full: [22 22 22 22 22]

full2d: 
[[35 35 35 35]
 [35 35 35 35]]


In [54]:
# Slicing

arr = np.array([45, 90, 25, 50, 35, 70, 15, 30, 65, 130])

print(f"arr[2 : 5]: {arr[2 : 5]}")
print(f"arr[ : 4]: {arr[ : 4]}")


arr2d = np.array([[20, 30, 10, 50], [35, 25, 75, 15]])

print(f"arr2d[0 : 2, 0 : 2]: \n{arr2d[0 : 2, 0 : 2]}\n")
print(f"arr2d[0, 1 : 3]: \n{arr2d[0, 1 : 3]}")
print(f"arr[ : , 2]: {arr2d[ : , 2]}\n")

arr[2 : 5]: [25 50 35]
arr[ : 4]: [45 90 25 50]
arr2d[0 : 2, 0 : 2]: 
[[20 30]
 [35 25]]

arr2d[0, 1 : 3]: 
[30 10]
arr[ : , 2]: [10 75]

