In [1]:
import numpy as np

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

array[[0, 1]] = array[[1, 0]]
array[:, [0, 1]] = array[:, [1, 0]]

print(f"array: \n{array}")

array: 
[[ 6  5  7  8]
 [ 2  1  3  4]
 [10  9 11 12]
 [14 13 15 16]]
