In [2]:
import numpy as np

In [21]:
array = np.random.randint(10, 100, (9, 9, 2))
extracted = array[2:7, 2:7, :]

print(extracted)

[[[94 21]
  [48 67]
  [97 52]
  [90 62]
  [80 87]]

 [[45 23]
  [24 94]
  [50 17]
  [87 94]
  [54 46]]

 [[37 99]
  [46 29]
  [98 87]
  [92 91]
  [12 51]]

 [[74 93]
  [18 39]
  [29 25]
  [21 86]
  [28 57]]

 [[98 54]
  [74 25]
  [13 29]
  [62 82]
  [86 85]]]
