In [1]:
import numpy as np

In [8]:
array = np.random.random((9, 9, 2))
extracted = array[2:7, 2:7, :]

print(extracted)

[[[0.51965953 0.26177533]
  [0.53103073 0.41985118]
  [0.69227423 0.76892244]
  [0.12047247 0.24766394]
  [0.06273042 0.38923119]]

 [[0.01660333 0.78167061]
  [0.13381862 0.52568617]
  [0.74871399 0.49576174]
  [0.73466841 0.34138219]
  [0.44739037 0.81078884]]

 [[0.27377665 0.06430041]
  [0.87401136 0.39353907]
  [0.96658569 0.15486016]
  [0.40023022 0.7455372 ]
  [0.44171066 0.52265872]]

 [[0.85707566 0.71417232]
  [0.4065873  0.2871494 ]
  [0.39773972 0.99426184]
  [0.38346232 0.73933306]
  [0.27550248 0.17782711]]

 [[0.74855918 0.94218269]
  [0.61772714 0.18443175]
  [0.84452961 0.79885812]
  [0.41375888 0.68053215]
  [0.4963663  0.30210481]]]
