In [28]:
import numpy as np

arr = np.array([2 ** x for x in range(6)]).reshape([2, 3])
print(f"Original array: \n{arr}\n")

print(f"Flatten: \n{arr.flatten()}\n")
print(f"Original array: \n{arr}\n\n")

print(f"Ravel: \n{arr.ravel()}\n")
print(f"Original array: \n{arr}")

Original array: 
[[ 1  2  4]
 [ 8 16 32]]

Flatten: 
[ 1  2  4  8 16 32]

Original array: 
[[ 1  2  4]
 [ 8 16 32]]


Ravel: 
[ 1  2  4  8 16 32]

Original array: 
[[ 1  2  4]
 [ 8 16 32]]
