In [1]:
import numpy as np

array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])

array3 = np.concatenate((array1, array2), axis=0)
print(f"Array3:\n{array3}\n")

array4 = np.concatenate((array1, array2), axis=1)
print(f"Array4:\n{array4}\n")

array5 = np.concatenate((array4, array4), axis=0)
print(f"Array5:\n{array5}\n")

array6 = np.concatenate((array3, array3), axis=1)
print(f"Array6:\n{array6}\n")

Array3:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]

Array4:
[[0 1 4 5]
 [2 3 6 7]]

Array5:
[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]

Array6:
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]

