In [7]:
import numpy as np

ones_array = np.ones([2, 3])
print(f"ones_array: \n{ones_array}\n")

zeros_array = np.zeros([3, 3])
print(f"zeros_array: \n{zeros_array}\n")

sevens_array = np.full([2, 5], 7)
print(f"sevens_array: \n{sevens_array}")

ones_array: 
[[1. 1. 1.]
 [1. 1. 1.]]

zeros_array: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

sevens_array: 
[[7 7 7 7 7]
 [7 7 7 7 7]]
