In [1]:
import numpy as np

In [10]:
# using bincount

random_array = np.random.randint(0, 100, (5, 5))
counts = np.bincount(random_array.flatten(), minlength=100)

print("Random array:\n", random_array)
print("Occurrences of each number (0–99):\n", counts, '\n')

Random array:
 [[29 34 45 57 13]
 [11 97 10 22 59]
 [93 53 95 18  6]
 [41 69 41 86 41]
 [95  6 96 22 75]]
Occurrences of each number (0–99):
 [0 0 0 0 0 0 2 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 2 0 0 0 0 0 0 1 0 0 0 0 1 0 0
 0 0 0 0 3 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 2 1 1 0 0] 



In [11]:
# without using bincount
random_array = np.random.randint(0, 100, (5, 5))
values, counts = np.unique(random_array, return_counts=True)

print(f"Random array: \n{random_array}\nOccurrences of each integer: \n{dict(zip(values, counts))}")

Random array: 
[[45 77 56 49 10]
 [95 86 92 95 39]
 [39 80 49 57 26]
 [68 97 29 40 98]
 [77 80 90 53 62]]
Occurrences of each integer: 
{10: 1, 26: 1, 29: 1, 39: 2, 40: 1, 45: 1, 49: 2, 53: 1, 56: 1, 57: 1, 62: 1, 68: 1, 77: 2, 80: 2, 86: 1, 90: 1, 92: 1, 95: 2, 97: 1, 98: 1}
