In [1]:
import numpy as np

arr = np.arange(1, 16)
arr = arr.reshape(3, 5)

print(f"Original Array (3x5):\n{arr}")

# (a) Select row 2
row_2 = arr[1, :]  # Row indices start at 0, so row 2 is index 1
print("\n(a) Row 2:")
print(row_2)

# (b) Select column 5
column_5 = arr[:, 4]  # Column indices start at 0, so column 5 is index 4
print("\n(b) Column 5:")
print(column_5)

# (c) Select rows 0 and 1
rows_0_and_1 = arr[0:2, :]  # Select rows 0 and 1 (index 0 and 1)
print("\n(c) Rows 0 and 1:")
print(rows_0_and_1)

# (d) Select columns 2-4
columns_2_to_4 = arr[:, 1:4]  # Select columns 2 to 4 (index 1 to 3)
print("\n(d) Columns 2-4:")
print(columns_2_to_4)

# (e) Select the element that is in row 1 and column 4
element_1_4 = arr[1, 4]  # Row 1, Column 4 (index 1, 4)
print("\n(e) Element at row 1 and column 4:")
print(element_1_4)

# (f) Select all elements from rows 1 and 2 that are in columns 0, 2, 4
elements_1_2_in_0_2_4 = arr[1:3, [0, 2, 4]]  # Rows 1 and 2 (index 1 and 2), columns 0, 2, 4 (index 0, 2, 4)
print("\n(f) Elements from rows 1 and 2 in columns 0, 2, 4:")
print(elements_1_2_in_0_2_4)

Original Array (3x5):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

(a) Row 2:
[ 6  7  8  9 10]

(b) Column 5:
[ 5 10 15]

(c) Rows 0 and 1:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

(d) Columns 2-4:
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

(e) Element at row 1 and column 4:
10

(f) Elements from rows 1 and 2 in columns 0, 2, 4:
[[ 6  8 10]
 [11 13 15]]
