In [1]:
import numpy as np

In [3]:
random_array = np.random.randint(0, 100, (5, 5))
values, counts = np.unique(random_array, return_counts=True)

print(f"Random array: \n{random_array}\nOccurrences of each integer: \n{dict(zip(values, counts))}")

Random array: 
[[52 60 65  7 20]
 [ 6 92 12 58 30]
 [58 79 37 66 73]
 [16 20 55  1 70]
 [63 71 35 38 65]]
Occurrences of each integer: 
{1: 1, 6: 1, 7: 1, 12: 1, 16: 1, 20: 2, 30: 1, 35: 1, 37: 1, 38: 1, 52: 1, 55: 1, 58: 2, 60: 1, 63: 1, 65: 2, 66: 1, 70: 1, 71: 1, 73: 1, 79: 1, 92: 1}
